version: "2"
services:
    web:
        image: klabs/apache:5.6
        hostname: web
        container_name: wp_web
        ports:
            - "80:80"
        volumes:
            - "~/www:/var/www:rw"
        env_file:
            - .env
            - wordpress.env
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}

    cli:
        image: klabs/php_cli:5.6
        hostname: cli
        container_name: wp_cli
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - "$SSH_AUTH_SOCK:/ssh-agent:ro"
            - "~/.gitconfig:/home/site/.gitconfig:ro"
            - "~/www:/var/www:rw"
        env_file:
            - .env
            - wordpress.env
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
        cap_add:
            - SYS_PTRACE

    mysql:
        image: klabs/mysql
        hostname: mysql
        container_name: wp_mysql
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql/
        env_file:
            - mysql.env
        cap_add:
            - SYS_PTRACE
        command: ["/root/bootstrap.sh", "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"]

volumes:
  mysql_data:
    driver: local

